name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-221.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.0.2
  dartz: ^0.10.1
  json_serializable: ^6.5.3
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  auto_route: ^5.0.2
  auto_route_generator: ^5.0.3
  flutter_hooks: ^0.18.5+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  lint: ^1.10.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
